# Generated by Django 5.2.10 on 2026-01-29 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='client_name',
            new_name='reviewer_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='message',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='order',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewer_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/Schools/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewer_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewer_title',
            field=models.CharField(blank=True, help_text='e.g., Principal, Admin Head', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='tag',
            field=models.CharField(blank=True, help_text='e.g. Quality, Delivery, Design, Support', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_duration',
            field=models.CharField(blank=True, help_text='e.g. 3:45', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_posted_ago',
            field=models.CharField(blank=True, help_text='e.g. 2 months ago', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/Products/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, etc.)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_views',
            field=models.CharField(blank=True, help_text='e.g. 12.5K views', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Star rating (1-5, optional for video)', max_digits=2, null=True),
        ),
    ]
