# Generated by Django 5.2.10 on 2026-01-30 09:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='section',
        ),
        migrations.DeleteModel(
            name='MapLocation',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='TopBarItem',
        ),
        migrations.AlterModelOptions(
            name='businessdetails',
            options={'verbose_name': 'Business Detail', 'verbose_name_plural': 'Business Details'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['order', 'number'], 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-review_date'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='trustedclient',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Trusted Client', 'verbose_name_plural': 'Trusted Clients'},
        ),
        migrations.RenameField(
            model_name='trustedclient',
            old_name='school_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='scroll_direction',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='feature',
            name='highlight',
            field=models.CharField(blank=True, help_text='Highlight tags (comma separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Display order/number'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('id-cards', 'ID Cards'), ('lanyards', 'Lanyards'), ('certificates', 'Certificates'), ('marksheets', 'Marksheets'), ('fee-cards', 'Fee Cards'), ('invitations', 'Invitations'), ('visiting-cards', 'Visiting Cards'), ('brochures', 'Brochures'), ('others', 'Others')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('portrait', 'Portrait'), ('landscape', 'Landscape'), ('featured', 'Featured'), ('', 'Default')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='trustedclient',
            name='cards_count',
            field=models.CharField(blank=True, help_text='e.g. 2000+ Cards', max_length=50),
        ),
        migrations.AddField(
            model_name='trustedclient',
            name='category',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College'), ('corporate', 'Corporate'), ('hospital', 'Hospital'), ('shop', 'Shop/Retail')], default='school', max_length=20),
        ),
        migrations.AddField(
            model_name='trustedclient',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trustedclient',
            name='location_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trustedclient',
            name='location_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trustedclient',
            name='status_badge',
            field=models.CharField(blank=True, choices=[('verified', 'Verified Client'), ('premium', 'Premium Client'), ('new', 'New Client'), ('', 'None')], default='verified', max_length=20),
        ),
        migrations.AddField(
            model_name='trustedclient',
            name='trusted_since_year',
            field=models.PositiveIntegerField(default=2026, help_text='Year since trusted (e.g. 2006)'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='socials',
            field=models.TextField(blank=True, help_text='Format: platform|url, e.g. facebook|https://fb.com/xyz (one per line)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(default='fas fa-shield-alt', help_text='Font Awesome icon class (e.g., fas fa-star)', max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Star rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='reviewer_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/Avatars/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='tag',
            field=models.CharField(blank=True, help_text='e.g. Quality, Delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/VideoThumbs/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube/Vimeo)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_views',
            field=models.CharField(blank=True, help_text='e.g. 1.2K', max_length=20),
        ),
        migrations.AlterField(
            model_name='trustedclient',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Alternative URL if image not available'),
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
        migrations.DeleteModel(
            name='FooterSection',
        ),
    ]
