# Generated by Django 5.2.17 on 2026-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("project_type", models.CharField(blank=True, max_length=150)),
                ("budget", models.CharField(blank=True, max_length=100)),
                ("preferred_date", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("contacted", "Contacted / Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="When True, rendered in bold high-contrast font as seen in Figma",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Industries",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Anishka", max_length=100)),
                (
                    "tagline",
                    models.CharField(default="Graphic Designing", max_length=150),
                ),
                ("hero_title", models.CharField(default="PORTFOLIO", max_length=100)),
                ("hero_year", models.CharField(default="2023", max_length=20)),
                (
                    "designer_sign",
                    models.CharField(default="Akash Kumar", max_length=100),
                ),
                (
                    "bio_heading",
                    models.CharField(default="Hi! I'm Anishka", max_length=150),
                ),
                (
                    "bio_paragraph_1",
                    models.TextField(
                        default="I'm a graphic designer with a passion for making things look good. I'm also pretty funny, so if you're looking for someone to design your next marketing campaign, you've come to the right place. Just don't expect me to take myself too seriously."
                    ),
                ),
                (
                    "bio_paragraph_2",
                    models.TextField(
                        default="I am a creative and innovative thinker with a strong attention to detail. I am always looking for new ways to improve my skills and knowledge."
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "hero_bg_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, default="https://instagram.com"),
                ),
                ("figma_url", models.URLField(blank=True, default="https://figma.com")),
                (
                    "behance_url",
                    models.URLField(blank=True, default="https://behance.net"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, default="https://linkedin.com"),
                ),
                (
                    "dribbble_url",
                    models.URLField(blank=True, default="https://dribbble.com"),
                ),
                ("phone", models.CharField(default="+1 (555) 019-2834", max_length=50)),
                (
                    "email",
                    models.EmailField(default="hello@anishka.design", max_length=254),
                ),
                (
                    "cta_title",
                    models.CharField(default="Feeling Confused?", max_length=100),
                ),
                (
                    "cta_subtext",
                    models.CharField(
                        default="I'd love to chat with you about how I can help.",
                        max_length=255,
                    ),
                ),
                (
                    "cta_bold_text",
                    models.CharField(default="Book a call today.", max_length=100),
                ),
                ("cta_btn_text", models.CharField(default="Call Now", max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Designer Profile",
                "verbose_name_plural": "Designer Profile",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Advertising", "Advertising & Marketing"),
                            ("Branding", "Brand Identity & Visuals"),
                            ("Packaging", "Packaging & Print"),
                            ("UI/UX", "Digital & UI/UX"),
                            ("Editorial", "Editorial & Publication"),
                            ("Art", "Art & Illustration"),
                        ],
                        default="Branding",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("client", models.CharField(blank=True, max_length=150)),
                ("year", models.CharField(default="2023", max_length=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("image_url_fallback", models.CharField(blank=True, max_length=500)),
                ("accent_color", models.CharField(default="#0066FF", max_length=30)),
                (
                    "tags",
                    models.CharField(
                        default="Design, Creative, Identity", max_length=255
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, help_text="e.g. Ps, Ai", max_length=10
                    ),
                ),
                (
                    "icon_type",
                    models.CharField(
                        choices=[
                            ("figma", "Figma"),
                            ("photoshop", "Photoshop"),
                            ("illustrator", "Illustrator"),
                            ("indesign", "InDesign"),
                            ("aftereffects", "After Effects"),
                            ("blender", "Blender"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                (
                    "icon_image",
                    models.ImageField(blank=True, null=True, upload_to="tools/"),
                ),
                ("proficiency", models.CharField(default="Expert", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
