# Generated by Django 5.2.17 on 2026-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=150)),
                ("institution", models.CharField(max_length=150)),
                ("period", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=150)),
                ("company", models.CharField(max_length=150)),
                ("location", models.CharField(default="Bhopal", max_length=100)),
                ("period", models.CharField(max_length=100)),
                (
                    "description_points",
                    models.TextField(help_text="Newline separated bullet points"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="alt_email",
            field=models.EmailField(default="mail@logicbyroshan.in", max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="Bhopal, Madhya Pradesh", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.URLField(
                blank=True, default="https://grafix.logicbyroshan.in"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="behance_url",
            field=models.URLField(
                blank=True, default="https://behance.net/logicbyroshan"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio_heading",
            field=models.CharField(default="Hi! I'm Roshan Damor", max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio_paragraph_1",
            field=models.TextField(
                default="I'm a professional graphic designer based in Bhopal, Madhya Pradesh with a Diploma in Graphics from Mantra Institute and a deep passion for digital branding and print-ready production. I specialize in crafting high-impact social media creatives, advertising campaigns, print brochures, and corporate ID card systems that make brands stand out."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio_paragraph_2",
            field=models.TextField(
                default="With industry experience at Adarsh ID Cards and Miracle Organisation, I bring end-to-end expertise across Photoshop, CorelDRAW, Lightroom, and Canva — bridging creative concept ideation with flawless industrial print and digital publishing."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cta_bold_text",
            field=models.CharField(default="logicbyroshan@gmail.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cta_btn_text",
            field=models.CharField(default="Contact Me", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cta_subtext",
            field=models.CharField(
                default="I'd love to chat with you about how I can help. Get in touch at",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="designer_sign",
            field=models.CharField(default="Roshan Damor", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dribbble_url",
            field=models.URLField(
                blank=True, default="https://dribbble.com/logicbyroshan"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="logicbyroshan@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="profile",
            name="figma_url",
            field=models.URLField(
                blank=True, default="https://figma.com/@logicbyroshan"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hero_year",
            field=models.CharField(default="2026", max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram_url",
            field=models.URLField(
                blank=True, default="https://instagram.com/logicbyroshan"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(
                blank=True, default="https://linkedin.com/in/logicbyroshan"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(default="Roshan Damor", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(default="+91 9179924975", max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(default="Advertising", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="year",
            field=models.CharField(default="2026", max_length=10),
        ),
        migrations.AlterField(
            model_name="tool",
            name="badge_text",
            field=models.CharField(
                blank=True, help_text="e.g. Ps, Cd, Lr", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="icon_type",
            field=models.CharField(default="custom", max_length=50),
        ),
    ]
