# Generated by Django 5.2.17 on 2026-09-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_education_experience_profile_alt_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "key",
                    models.CharField(
                        help_text="Short key e.g. Advertising, Branding",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Description displayed under the category header",
                        max_length=300,
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="Layers",
                        help_text="Lucide icon name e.g. Megaphone, CreditCard, Package, Camera, BookOpen, Sparkles",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio_paragraph_1",
            field=models.TextField(
                default="I'm a graphic designer based in Bhopal, Madhya Pradesh with a Diploma in Graphics from Mantra Institute and expertise in digital branding, advertising creatives, and industrial print production. Whether you need trend-focused social media visuals, print-ready brochures, corporate ID card systems, or photo retouching, I craft designs that command attention."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio_paragraph_2",
            field=models.TextField(
                default="With hands-on experience at Adarsh ID Cards and Miracle Organisation, I work seamlessly across Adobe Photoshop, CorelDRAW, Lightroom, and Canva — turning marketing ideas into pixel-perfect digital visuals and print-ready deliverables."
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                default="Advertising",
                help_text="Category key matching Category.key",
                max_length=100,
            ),
        ),
    ]
