# Generated by Django 5.2.17 on 2026-09-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_category_alter_profile_bio_paragraph_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callbooking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="callbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("contacted", "Contacted / Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="key",
            field=models.CharField(
                db_index=True,
                help_text="Short key e.g. Advertising, Branding",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="education",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="experience",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="industry",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cta_bold_text",
            field=models.CharField(default="mail@logicbyroshan.in", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                db_index=True,
                default="Advertising",
                help_text="Category key matching Category.key",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="tool",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
