# Generated by Django 5.2.7 on 2026-09-26 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_alter_callbooking_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callbooking",
            name="consent_given",
            field=models.BooleanField(
                default=True,
                help_text="Explicit DPDP consent granted by Data Principal",
            ),
        ),
        migrations.AddField(
            model_name="callbooking",
            name="consent_notice_version",
            field=models.CharField(
                default="1.0",
                help_text="Version of Privacy Notice presented",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="callbooking",
            name="consent_purpose",
            field=models.CharField(
                default="Consultation & Project Inquiry Communication",
                help_text="Specified purpose for personal data processing",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="callbooking",
            name="consent_timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when DPDP consent was recorded",
            ),
        ),
        migrations.AddField(
            model_name="callbooking",
            name="ip_hash",
            field=models.CharField(
                blank=True,
                help_text="Pseudonymised SHA-256 hash of client IP for consent audit trail",
                max_length=64,
            ),
        ),
    ]
